const texture = {
    emerald: "minecraft:emerald",
    amethyst: "minecraft:amethyst_shard",
    gold: "minecraft:gold_ingot"
};
export const titleRegistry = [
    { price: 100, color: "§a", name: "100-air", texture: texture.emerald },
    { price: 100, color: "§a", name: "Peasant", texture: texture.emerald },
    { price: 100, color: "§a", name: "Bot", texture: texture.emerald },
    { price: 100, color: "§a", name: "Name:", texture: texture.emerald },
    { price: 100, color: "§a", name: "Builder:", texture: texture.emerald },
    { price: 250, color: "§a", name: "Lady", texture: texture.emerald },
    { price: 250, color: "§a", name: "Mister", texture: texture.emerald },
    { price: 250, color: "§a", name: "Trader", texture: texture.emerald },
    { price: 250, color: "§a", name: "Traitor", texture: texture.emerald },
    { price: 250, color: "§a", name: "Miner:", texture: texture.emerald },
    { price: 500, color: "§a", name: "Peach", texture: texture.emerald },
    { price: 500, color: "§a", name: "Farmer:", texture: texture.emerald },
    { price: 500, color: "§a", name: "Stewart", texture: texture.emerald },
    { price: 500, color: "§a", name: "Princess", texture: texture.emerald },
    { price: 500, color: "§a", name: "Ms.", texture: texture.emerald },
    { price: 1000, color: "§9", name: "Thousand-air", texture: texture.amethyst },
    { price: 1000, color: "§9", name: "Raider", texture: texture.amethyst },
    { price: 1000, color: "§9", name: "Mobster", texture: texture.amethyst },
    { price: 1000, color: "§9", name: "Lieutenant", texture: texture.amethyst },
    { price: 1000, color: "§9", name: "Maiden", texture: texture.amethyst },
    { price: 2500, color: "§9", name: "Chief", texture: texture.amethyst },
    { price: 2500, color: "§9", name: "Sargent", texture: texture.amethyst },
    { price: 2500, color: "§9", name: "Lord", texture: texture.amethyst },
    { price: 2500, color: "§9", name: "Knight", texture: texture.amethyst },
    { price: 2500, color: "§9", name: "Dr.", texture: texture.amethyst },
    { price: 1000000, color: "§e", name: "Milionaire", texture: texture.gold },
    { price: 1000000, color: "§e", name: "Bezos", texture: texture.gold },
    { price: 1000000, color: "§e", name: "Stanky", texture: texture.gold },
    { price: 1000000, color: "§e", name: "Expert", texture: texture.gold },
    { price: 1000000, color: "§e", name: "Official", texture: texture.gold },
];
