export const itemSelldefaultPrice = 0.001;

export type ItemSellPrice = {
  item: string,
  price: number,
  type?: boolean
}

export const itemSellPriceRegistry = [
  { item: "minecraft:nether_star", price: 25 },
  { item: "minecraft:diamond", price: 1 },
  { item: "minecraft:gold_ingot", price: 0.08 },
  { item: "minecraft:obsidian", price: 0.064 },
  { item: "minecraft:iron_ingot", price: 0.064 },
  { item: "minecraft:raw_gold", price: 0.64 },
  { item: "concrete", price: 0.064, includes: true },

  { item: "minecraft:wheat", price: 0.048 },
  { item: "minecraft:carrots", price: 0.048 },
  { item: "minecraft:potatoes", price: 0.048 },
  { item: "minecraft:beetroot", price: 0.048 },
  { item: "minecraft:sweet_berry_bush", price: 0.048 },
  { item: "minecraft:nether_wart", price: 0.048 },
  { item: "minecraft:cocoa", price: 0.048 },
  { item: "minecraft:cactus", price: 0.048 },
  { item: "minecraft:reeds", price: 0.048 },
  { item: "minecraft:torchflower", price: 0.048 },
  { item: "minecraft:pitcher_crop", price: 0.048 },

  { item: "minecraft:beef", price: 0.048 },
  { item: "minecraft:mutton", price: 0.048 },
  { item: "minecraft:chicken", price: 0.048 },
  { item: "minecraft:rabbit", price: 0.048 },
  { item: "minecraft:cod", price: 0.048 },
  { item: "minecraft:salmon", price: 0.048 },
  { item: "minecraft:raw_iron", price: 0.048 },
  { item: "minecraft:emerald", price: 0.048 },

  { item: "blackstone", price: 0.032, includes: true },
  { item: "minecraft:gravel", price: 0.032 },
  { item: "glazed", price: 0.032, includes: true },
  { item: "minecraft:gravel", price: 0.032 },
  { item: "minecraft:sand", price: 0.032 },
  { item: "wood", price: 0.032, includes: true },
  { item: "minecraft:coal", price: 0.032 },
  { item: "minecraft:raw_copper", price: 0.032 },

  { item: "minecraft:dirt", price: 0.016 },
  { item: "minecraft:stone", price: 0.016 },
  { item: "minecraft:granite", price: 0.016 },
  { item: "minecraft:diorite", price: 0.016 },
  { item: "minecraft:andesite", price: 0.016 },
  { item: "seed", price: 0.016 },
  { item: "leaves", price: 0.016 },
  { item: "grass", price: 0.016 },

  { item: "door", price: 0.008 },
  { item: "pressure", price: 0.008 },
  { item: "basalt", price: 0.008 },
  { item: "cobblestone", price: 0.008 },
  { item: "slab", price: 0.008 },
  { item: "stair", price: 0.008 },
  { item: "wall", price: 0.008 },
  { item: "fence", price: 0.008 },

  { item: "minecraft:redstone", price: 0.008 },
  { item: "minecraft:redstone_torch", price: 0.008 },
  { item: "minecraft:redstone_block", price: 0.008 },
  { item: "minecraft:redstone_lamp", price: 0.008 },
  { item: "minecraft:lever", price: 0.008 },
  { item: "minecraft:repeater", price: 0.008 },
  { item: "minecraft:comparator", price: 0.008 },
  { item: "minecraft:daylight_detector", price: 0.008 },
  { item: "minecraft:tripwire_hook", price: 0.008 },
  { item: "minecraft:trapped_chest", price: 0.008 },
  { item: "minecraft:observer", price: 0.008 },
  { item: "minecraft:piston", price: 0.008 },
  { item: "minecraft:sticky_piston", price: 0.008 },
  { item: "minecraft:dispenser", price: 0.008 },
  { item: "minecraft:dropper", price: 0.008 },
  { item: "minecraft:noteblock", price: 0.008 },
  { item: "minecraft:tnt", price: 0.008 },
  { item: "minecraft:sculk_sensor", price: 0.008 },
  { item: "minecraft:target", price: 0.008 },
  { item: "minecraft:golden_rail", price: 0.008 },
  { item: "minecraft:detector_rail", price: 0.008 },
  { item: "minecraft:activator_rail", price: 0.008 },
  { item: "minecraft:lightning_rod", price: 0.008 },
  { item: "minecraft:bell", price: 0.008 },

  //...
]